In [ ]:
import numpy as np

# **HW2 LA4DS**

## Task 1

In [ ]:
A = np.matrix([[-56, -4, 30, 59], [-76, -32, -33, -74], [76, 56, -18, -22]])

In [ ]:
U, E, V = np.linalg.svd(A)

In [ ]:
ee = np.matrix([[135, 0, 0, 0], [0, 108, 0, 0], [0, 0, 27, 0]])

In [ ]:
V * 9

matrix([[-8.00000000e+00, -4.00000000e+00, -4.49640325e-15,
         -1.00000000e+00],
        [ 1.00000000e+00,  5.62050406e-15, -4.00000000e+00,
         -8.00000000e+00],
        [ 4.00000000e+00, -8.00000000e+00,  1.00000000e+00,
         -4.99600361e-16],
        [ 1.23292455e-15, -1.00000000e+00, -8.00000000e+00,
          4.00000000e+00]])

In [ ]:
vv = np.matrix([[-8, -4, 0, -1], [1, 0, -4, -8], [4, -8, 1, 0], [0, -1, -8, 4]]) * 1/9

In [ ]:
U @ ee @ vv

matrix([[-56.,  -4.,  30.,  59.],
        [-76., -32., -33., -74.],
        [ 76.,  56., -18., -22.]])

In [ ]:
ee1 = np.matrix([[135, 0, 0, 0], [0, 108, 0, 0], [0, 0, 0, 0]])

In [ ]:
U @ ee1 @ vv

matrix([[-48., -20.,  32.,  59.],
        [-72., -40., -32., -74.],
        [ 84.,  40., -16., -22.]])

In [ ]:
delta = U @ ee @ vv - U @ ee1 @ vv

In [ ]:
delta

matrix([[-8., 16., -2.,  0.],
        [-4.,  8., -1.,  0.],
        [-8., 16., -2.,  0.]])

In [ ]:
np.linalg.norm(delta)

27.0

## Task 2

In [ ]:
A = np.matrix([[-3.05, -0.06], [-0.13, -8.05]])
b = np.array([[-2.89], [-7.98]])

In [ ]:
#Ax = b => x = A.inv b
np.linalg.inv(np.matrix.round(A)) * np.matrix.round(b)

matrix([[1.],
        [1.]])

In [ ]:
# np.linalg.inv(np.matrix.round(A)) * 24

matrix([[-8.,  0.],
        [ 0., -3.]])

In [ ]:
Ainv = np.linalg.inv(np.matrix.round(A))

In [ ]:
np.sum(np.absolute(np.matrix.round(A)), axis = 1), np.sum(np.absolute(Ainv), axis = 1) * 24

(matrix([[3.],
         [8.]]),
 matrix([[8.],
         [3.]]))

In [ ]:
_, s, _ = np.linalg.svd(np.transpose(np.matrix.round(A)) @ np.matrix.round(A))
s

array([64.,  9.])

In [ ]:
_, s, _ = np.linalg.svd(np.transpose(A - np.round(A)) @ (A - np.round(A)))
np.max(np.sqrt(s))

0.15603277807866872

In [ ]:
_, s, _ = np.linalg.svd(np.transpose(A) @ A)
np.max(np.sqrt(s))

8.051914708128173

In [ ]:
np.linalg.norm(b - np.round(b))

0.11180339887498929

## Task 3

In [ ]:
A, b = np.matrix([[4, -2], [-4, -1]]), np.matrix([[3], [4]])
np.linalg.inv(A) * b * 12

matrix([[ -5.],
        [-28.]])

In [ ]:
np.linalg.inv(A) * 12

matrix([[ 1., -2.],
        [-4., -4.]])

In [ ]:
_, s, _ = np.linalg.svd(np.transpose(A) @ A)
np.sqrt(s)

array([5.70790048, 2.1023492 ])

In [ ]:
deltaA = np.matrix([[0.05, 0.1], [0, 0.05]])

In [ ]:
_, s, _ = np.linalg.svd(np.transpose(deltaA) @ deltaA)
np.sqrt(s)

array([0.12071068, 0.02071068])

## Task 4

In [ ]:
A = np.matrix([[5, -1], [-2, -3]])

In [ ]:
np.linalg.inv(A) * 17

matrix([[ 3., -1.],
        [-2., -5.]])

In [ ]:
42 / 17 * (0.02 / 6) / (1 - 42 / 17 * (0.02 / 6))

0.008303677342823251

## Task 5

In [89]:
A, b = np.matrix([[25, 6, 4], [2, 23, 2], [6, 1, 25]]), np.array([5, 9, 1])
x0 = np.array([0, 0, 0])

In [90]:
L, D, R = np.tril(A, -1), np.diag(np.diag(A)), np.triu(A, 1)

In [91]:
inv_D = np.linalg.inv(D)
P = inv_D @ (-(L + R))
c = inv_D @ b

In [92]:
i = 1
while True:
    x_next = P @ x0 + c
    error = np.linalg.norm(x_next - x0)
    x0 = x_next

    # print(f"{i}) error={error}")

    if error < 0.01:
        print(f"\nEnd on {i} iteration")
        break

    i += 1

x0

1) error=0.44126986372014937
2) error=0.12062273702785366
3) error=0.03247489001891268
4) error=0.009209307392144957

End on 4 iteration


array([ 0.10747253,  0.38120541, -0.00295891])

# Task 6

In [ ]:
A = np.matrix([[1, 0, 1, 1, 1], [0, 0, 1, 0, 1], [0, 1, 0, 1, 1], [0, 1, 0, 0, 0], [0, 0, 1, 1, 1]])

In [ ]:
norm_A = A / A.sum(axis=1)
P = np.transpose(norm_A)

In [ ]:
beta = 0.15
Q = np.ones((5, 5)) / 5
PR = (1 - beta) * P + beta * Q
PR

matrix([[0.2425    , 0.03      , 0.03      , 0.03      , 0.03      ],
        [0.03      , 0.03      , 0.31333333, 0.88      , 0.03      ],
        [0.2425    , 0.455     , 0.03      , 0.03      , 0.31333333],
        [0.2425    , 0.03      , 0.31333333, 0.03      , 0.31333333],
        [0.2425    , 0.455     , 0.31333333, 0.03      , 0.31333333]])

In [ ]:
eigvals, eigvecs = np.linalg.eig(PR)
index = np.argmin(np.abs(eigvals - 1))
vec = eigvecs[:, index].reshape(1, -1)
vec, vec.argmax()

(matrix([[-0.07794921+0.j, -0.51788462+0.j, -0.46834598+0.j,
          -0.38094304+0.j, -0.601044  +0.j]]),
 0)